name: My First Workflow
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run multi-line shell commands using pipe symbol
        run: |
          echo "First Output"
          echo "Second Output"
