name: GitHub Context Object & Expressions
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Get github object metadata
        run: echo "${{ toJson(github) }}"